### ISSUE TITLE
Error while parsing schematic

### ISSUE THREAD

**Issue by Rattlyy** [MorganAnkan/schembuildbot#2]
C:\Users\giova\OneDrive\Desktop\schembuildbot-master\main.js:215                                                                if (testBlock.name == schemBlock.block.name && schemBlock.block.facing == testBlock.getProperties().facing)                                                    ^                                                                                                                                                                                                TypeError: Cannot read property 'name' of undefined                                                                         at C:\Users\giova\OneDrive\Desktop\schembuildbot-master\main.js:215:48                                                  at Array.forEach (<anonymous>)                                                                                          at build (C:\Users\giova\OneDrive\Desktop\schembuildbot-master\main.js:200:10)                                          at C:\Users\giova\OneDrive\Desktop\schembuildbot-master\main.js:186:24                                                  at C:\Users\giova\OneDrive\Desktop\schembuildbot-master\schematic-parser.js:15:9                                        at Gunzip.cb (C:\Users\giova\OneDrive\Desktop\schembuildbot-master\node_modules\prismarine-nbt\nbt.js:45:9)

**Comment by MorganAnkan** [comment]
the bot probably didnt have time to render the world cause "testBlock" is a world block and "schemBlock" is a block of the schematic

**Comment by MorganAnkan** [comment]
so just waiting like 1minute before using it should work, also sorry for extremely late response im almost never on github

**Comment by Rattlyy** [comment]
> so just waiting like 1minute before using it should work, also sorry for extremely late response im almost never on github

bro 1 year has passed i totally forgot about this
